[default]
timeout = 180

[musicbank]
title = "뮤직뱅크"
url = "https://program.naver.com/p/659774/clip"
entrySelector = "ul.ClipCardList_wrap__2K642 li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
contentSelector = "span.ClipCard_time__128vc"
waitForSelector = "li.ClipCard_item__1ly4h"
onFail = "stale"